# Nome do Workflow que aparecerá na aba Actions do GitHub
name: Deploy Terraform Infrastructure

# Controla quando o workflow será executado
on:
  push:
    branches:
      - main # Executa somente em push para a branch 'main'
  # workflow_dispatch: # Descomente esta linha se quiser acionar manualmente também

# Define os jobs que o workflow executará
jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest # Usa um runner Linux padrão do GitHub

    # Passos executados sequencialmente
    steps:
      # 1. Baixa o código do repositório para o runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura as credenciais da AWS
      #    Você PRECISA configurar os Secrets 'AWS_ACCESS_KEY_ID' e 'AWS_SECRET_ACCESS_KEY'
      #    nas configurações do seu repositório GitHub (Settings > Secrets and variables > Actions)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1 # Sua região AWS

      # 3. Instala o Terraform CLI
      #    Você pode especificar uma versão exata se precisar
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: 1.8.0 # Exemplo: Fixar versão

      # 4. Inicializa o Terraform (baixa provedores)
      - name: Terraform Init
        id: init
        run: terraform init

      # 5. Valida a configuração Terraform (verifica sintaxe)
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # 6. Gera o plano de execução Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        # continue-on-error: true # Descomente se quiser que o workflow continue mesmo se o plan falhar (não recomendado para apply direto)

      # 7. Aplica a configuração Terraform
      #    O '-auto-approve' aplica automaticamente SEM pedir confirmação.
      #    Use com CUIDADO, especialmente na branch 'main'.
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false